project:
  type: website
  output-dir: docs

website:
  title: "Gigi Mordock"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Offensive-Defensive.qmd 
        text: Offense vs. Defense  

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    mainfont: times-new-roman
    fontsize: 20px

editor: visual

