project:
  type: website
  output-dir: docs
render: 
- index.qmd
- Project.qmd

website:
  title: "Gigi Mordock"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Project.qmd 
        text: Project 

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    mainfont: times-new-roman
    fonstize: 20px

editor: visual

